# Generated by Django 3.0.8 on 2020-07-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monday_model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('firstperiod', models.CharField(max_length=30)),
                ('secondperiod', models.CharField(max_length=30)),
                ('thirdperiod', models.CharField(max_length=30)),
                ('fourthperiod', models.CharField(max_length=30)),
                ('fifthperiod', models.CharField(max_length=30)),
                ('sixthperiod', models.CharField(max_length=30)),
                ('seventhperiod', models.CharField(max_length=30)),
                ('eightperiod', models.CharField(max_length=30)),
            ],
        ),
    ]
