# Generated by Django 3.0.8 on 2020-07-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='column_model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodno', models.IntegerField()),
                ('monday', models.CharField(max_length=30)),
                ('tuesday', models.CharField(max_length=30)),
                ('wednesday', models.CharField(max_length=30)),
                ('thrusday', models.CharField(max_length=30)),
                ('friday', models.CharField(max_length=30)),
                ('saturday', models.CharField(max_length=30)),
            ],
        ),
    ]
